# Pre-commit hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer  # Asegura que haya una línea en blanco al final de los archivos
      - id: trailing-whitespace  # Elimina espacios en blanco al final de las líneas

  - repo: https://github.com/prettier/pre-commit
    rev: v1.4.0
    hooks:
      - id: prettier  # Formatea archivos soportados por Prettier (HTML, CSS, JS, TS, JSON)
        args:
          - --write

  - repo: https://github.com/typicode/husky
    rev: v8.0.3
    hooks:
      - id: husky  # Agrega soporte para hooks de Git configurados en tu proyecto

  - repo: https://github.com/denoland/deno_lint
    rev: v0.43.0
    hooks:
      - id: deno-lint  # Linter para TypeScript y JavaScript
        name: Deno Lint
        language: system
        entry: deno lint
        types: [typescript, javascript]

  - repo: https://github.com/marionebl/commitlint
    rev: v17.7.0
    hooks:
      - id: commitlint  # Verifica que los mensajes de commit cumplan con las convenciones
        language: system
        entry: npx commitlint --edit
        pass_filenames: false

  - repo: https://github.com/microsoft/tslint
    rev: v6.1.3
    hooks:
      - id: tslint  # Linter para TypeScript (si prefieres TSLint en lugar de ESLint)
        args: ["--project", "./tsconfig.json"]
